### ISSUE TITLE
Error: Terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by zihhuafang** [kensung-lab/SurVTyper#1]
Hi,
Thank you very much for developing the suite of SV calling tools. 
I am using INSurVeyor and SurVIndel2 to call SVs for individual samples, and then performing clustering across individual callsets using SurVClusterer to generate population-level SV calls. I then genotype these population-level SV calls using SurVTyper.

For some of the samples, I have encountered the following error:
`terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551612) > this->size() (which is 46)
Aborted (core dumped)`

I am not sure why this only happens with some samples and not all, and I’m unsure how to troubleshoot this issue. 
Would you be able to provide any advice?

Thank you in advance!

**Comment by Mesh89** [comment]
Hi,
Is the data you are using private? Would it be possible for me to try it?

**Comment by zihhuafang** [comment]
Is private but can share the data. Can I have your email to send over the files?

**Comment by Mesh89** [comment]
You can use attach @ gmail.com to my username.

**Comment by Mesh89** [comment]
I pushed a bug-fix. I am able to run the sample you provided. Let me know if you have any problem with it.

**Comment by zihhuafang** [comment]
I confirmed it works on my end as well!
Thanks a lot!

Just wondering if you have a ballpark estimate of the memory required?
I am running on 1 cpu with 20G, and it failed quite often for chr1 and 2.
Doesn't look like it's related to the size of cram (coverage) based on my experience. 
Should I split into smaller chuncks?

**Comment by Mesh89** [comment]
Running the file you provided (which only contains chr14 variants) took me around 15 GB.
If chr1 and 2, which probably have more variants, fail often, you may try and divide them into smaller chunks. 

Note that although variants are genotyped independently, there is an overhead for each vcf file you process, dividing the into too many files would be very inefficient.

**Comment by zihhuafang** [comment]
Thanks a lot for sharing this. 
The mem requirement is similar to what I've seen on average.
I will just scale the mem according to the chromosomes then. 

Thanks again!
